export const categoryList = [
  // {
  //   id: 1,
  //   value: 'place',
  //   label: '🚩 Places',
  // },
  // {
  //   id: 2,
  //   value: 'dish',
  //   label: '🍕 Dishes',
  // },
];

export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5🌟',
  },
];

export const dataList = [
  {
    id: 1,
    title: <a style={{color:'black', textDecoration:'none'}} href="/teacherprofile"> Teacher Henock</a>,
    serviceTime: 'henock@gmail.com',
    deliveryFee: 3.44,
    category: 'place',
    cuisine: 'physics',
    rating: 5,
    price: 2500,
    coverSrc: '/images/places/profile.png',
  },
  {
    id: 2,
    title: <a style={{color:'black', textDecoration:'none'}} href="/teacherprofile">Teacher Nahom</a>,
    serviceTime: 'nahom@gmail.com',
    deliveryFee: 4.94,
    category: 'place',
    cuisine: 'biology',
    rating: 4,
    price: 1000,
    coverSrc: '/images/places/profile.png',
  },
  {
    id: 3,
    title: <a style={{color:'black', textDecoration:'none'}} href="/teacherprofile">Teacher Nahom</a>,
    serviceTime: 'nahom@gmail.com',
    deliveryFee: 4.94,
    category: 'place',
    cuisine: 'chemistry',
    rating: 3,
    price: 2000,
    coverSrc: '/images/places/profile.png',
  },
  {
    id: 4,
    title: <a style={{color:'black', textDecoration:'none'}} href="/teacherprofile">Teacher Nahom</a>,
    serviceTime: 'nahom@gmail.com',
    deliveryFee: 2.14,
    category: 'place',
    cuisine: 'physics',
    rating: 1,
    price: 1800,
    coverSrc: '/images/places/profile.png',
  },
  {
    id: 5,
    title: <a style={{color:'black', textDecoration:'none'}} href="/teacherprofile">Teacher Abel</a>,
    serviceTime: 'abel@gmail.com',
    deliveryFee: 6.79,
    category: 'place',
    cuisine: 'biology',
    rating: 5,
    price: 2000,
    coverSrc: '/images/places/profile.png',
  },
  {
    id: 6,
    title: <a style={{color:'black', textDecoration:'none'}} href="/teacherprofile">Teacher Abel</a>,
    serviceTime: 'abel@gmail.com',
    deliveryFee: 2.87,
    category: 'place',
    cuisine: 'chemistry',
    rating: 5,
    price: 3500,
    coverSrc: '/images/places/profile.png',
  },
  {
    id: 7,
    title: <a style={{color:'black', textDecoration:'none'}} href="/teacherprofile">Teacher Abel</a>,
    serviceTime: 'abel@gmail.com',
    deliveryFee: 8.5,
    category: 'dish',
    cuisine: 'physics',
    rating: 2,
    price: 2200,
    coverSrc: '/images/places/profile.png',
  },
  {
    id: 8,
    title: <a style={{color:'black', textDecoration:'none'}} href="/teacherprofile">Teacher Abel</a>,
    serviceTime: 'abel@gmail.com',
    deliveryFee: 1.8,
    category: 'dish',
    cuisine: 'biology',
    rating: 1,
    price: 1900,
    coverSrc: '/images/places/profile.png',
  },
  {
    id: 9,
    title: <a style={{color:'black', textDecoration:'none'}} href="/teacherprofile">Teacher Gedion</a>,
    serviceTime: 'gedion@gmail.com',
    deliveryFee: 3.33,
    category: 'dish',
    cuisine: 'chemistry',
    rating: 4,
    price: 2750,
    coverSrc: '/images/places/profile.png',
  },
  {
    id: 10,
    title: <a style={{color:'black', textDecoration:'none'}} href="/teacherprofile">Teacher Gedion</a>,
    serviceTime: 'gedion@gmail.com',
    deliveryFee: 1.9,
    category: 'dish',
    cuisine: 'physics',
    rating: 2,
    price: 4350,
    coverSrc: '/images/places/profile.png',
  },
  {
    id: 11,
    title: <a style={{color:'black', textDecoration:'none'}} href="/teacherprofile">Teacher Gedion</a>,
    serviceTime: 'gedion@gmail.com',
    deliveryFee: 4.1,
    category: 'dish',
    cuisine: 'biology',
    rating: 3,
    price: 3300,
    coverSrc: '/images/places/profile.png',
  },
  {
    id: 12,
    title: <a style={{color:'black', textDecoration:'none'}} href="/teacherprofile">Teacher Gedion</a>,
    serviceTime: 'gedion@gmail.com',
    deliveryFee: 1.5,
    category: 'dish',
    cuisine: 'chemistry',
    rating: 2,
    // price: 4100,
    coverSrc: '/images/places/profile.png',
  },
];
